version: '3.3'

services:
  react:
    build: ./src
    image: node:8
    depends_on:
       - api
    volumes:
      - .:/usr/src/app
    restart: always
    ports:
      - 3000:3000
    links:
      - db
      - api
    command: npm run react:start
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=react
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
  api:
    build: ./api
    image: node:8
    env_file: ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
    restart: always
    ports:
      - 3005:3005
    environment:
      - PORT=3005