version: '3.3'

services:
  react:
    build: 
      context: .
      dockerfile: ./Dockerfile.react
    image: local/react
    depends_on:
       - api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/    # mounts empty folder so npm can install on the image
    restart: always
    ports:
      - 3000:3000
    links:
      - db
      - api
    command: npm run react:start
  db:
    image: mysql:5.7
    restart: "no"
    #volumes:
      #- ./data/mysql:/var/lib/mysql    # Mac/Linux: uncomment to persist data
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=react
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.express 
    image: local/express
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/    # mounts empty folder so npm can install on the image
    restart: always
    ports:
      - 3001:3001
    environment:
      - PORT=3001